### ISSUE TITLE
Does not work with alternative pronunciation "zwo"

### ISSUE THREAD

**Issue by thiborose** [walu2/zahlwort2num#4]
```py
>>> from zahlwort2num import convert
>>> convert("zwo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\miniforge3\lib\site-packages\zahlwort2num\__init__.py", line 137, in convert
    return c.convert()
  File "C:\ProgramData\miniforge3\lib\site-packages\zahlwort2num\__init__.py", line 123, in convert
    return self.ordBn(number)
  File "C:\ProgramData\miniforge3\lib\site-packages\zahlwort2num\__init__.py", line 108, in ordBn
    return self.ordWithBN(number, 0)
  File "C:\ProgramData\miniforge3\lib\site-packages\zahlwort2num\__init__.py", line 88, in ordWithBN
    return self.convOrd(number)
  File "C:\ProgramData\miniforge3\lib\site-packages\zahlwort2num\__init__.py", line 81, in convOrd
    return self.convt2(number)
  File "C:\ProgramData\miniforge3\lib\site-packages\zahlwort2num\__init__.py", line 129, in <lambda>
    self.convt2 = lambda number: self.mult(number, 'tausend', 1000, self.convh2)
  File "C:\ProgramData\miniforge3\lib\site-packages\zahlwort2num\__init__.py", line 60, in mult
    return fun(spliter[0])
  File "C:\ProgramData\miniforge3\lib\site-packages\zahlwort2num\__init__.py", line 130, in <lambda>
    self.convh2 = lambda number: self.mult(number, 'hundert', 100, self.convu2)
  File "C:\ProgramData\miniforge3\lib\site-packages\zahlwort2num\__init__.py", line 60, in mult
    return fun(spliter[0])
  File "C:\ProgramData\miniforge3\lib\site-packages\zahlwort2num\__init__.py", line 131, in <lambda>
    self.convu2 = lambda number: self.mult(number, 'und', 1, lambda word: self.CONST_NUMS[word])
  File "C:\ProgramData\miniforge3\lib\site-packages\zahlwort2num\__init__.py", line 60, in mult
    return fun(spliter[0])
  File "C:\ProgramData\miniforge3\lib\site-packages\zahlwort2num\__init__.py", line 131, in <lambda>
    self.convu2 = lambda number: self.mult(number, 'und', 1, lambda word: self.CONST_NUMS[word])
KeyError: 'zwo'
```

**Comment by walu2** [comment]
Hi @psawa thanks for your suggestion. Indeed it looks there is such form https://de.wiktionary.org/wiki/zwo - acc to this it looks to be form borrowed from Old High German but as still in use so I dont see any obstacles to support it as well here 👍  

I'd appreciate if you could double check [test suite ](https://github.com/Wortmeister-HQ/zahlwort2num/blob/master/zahlwort2num/tests/test_convert.py) (to see nothing will be broken through that) and to extend with some cases using `zwo`. 

Having this Im happy to merge. Cheers!

**Comment by thiborose** [comment]
You're welcome, thanks for this awesome library! 
I created a new pull request  that includes a handful of new test cases: https://github.com/Wortmeister-HQ/zahlwort2num/pull/6. The tests passed on my side.

**Comment by walu2** [comment]
FYI - Merged and version bumped. Thx!
